---
title: "AugspurgerSynchrony"
author: "sagesteppe"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
fig_caption: yes
vignette: >
  %\VignetteIndexEntry{AugspurgerSynchrony}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This package includes a single function which serves to calculate Augspurgers Index of Synchrony.

The package can be installed from either github, using the remotes package, or CRAN. For most users I recommend installing from CRAN. 

```{r Install package, eval = F}
# install.packages('remotes', dependencies = T)
remotes::install_github('sagesteppe/AugspurgIndex') # one option 
install.packages('AugspurgerIndex')
```

```{r attach package to session, message = F, warning = F, eval = F}
library(AugspurgerIndex)
```


```{r import and view structure of data, eval = F}

flowering_data <- data('flowering_data')

head(flowering_data)
```

```{r run function, eval = F}

synchrony <- augs_synchrony(dataset = flowering_data,
                             frst_day = flower_start, lst_day = flower_end,
                             year_samp = year, species )
head(synchrony)

test_dummyp <- synchrony |>
  dplyr::group_by(species) |> 
  dplyr::mutate(ID = 1:dplyr::n(),
                flower_start_DOY = lubridate::yday(flower_start),
                flower_end_DOY   = lubridate::yday(flower_end))

```


